apiVersion: apps/v1
kind: Deployment
metadata:
  name: about
  labels:
    app: about
spec:
  replicas: 3
  selector:
    matchLabels:
      app: about
  template:
    metadata:
      labels:
        app: about
    spec:
      containers:
      - name: about
        image: miggylol/about
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: about
  labels:
    app: about
spec:
  type: NodePort
  selector:
    app: about
  ports:
  - protocol: TCP
    port: 8081
