apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc1
  labels:
    app: svc1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: svc1
  template:
    metadata:
      labels:
        app: svc1
    spec:
      containers:
      - name: svc1
        image: miggylol/svc1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc1
  labels:
    app: svc1
spec:
  type: NodePort
  selector:
    app: svc1
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
