apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gcp-ingress
spec:
  rules:
  - http:
      paths:
      - path: /h/home/*
        backend:
          serviceName: home
          servicePort: 8080
      - path: /a/about/*
        backend:
          serviceName: about
          servicePort: 8081
